easyhealth_app/routes.py
import os
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from easyhealth_app.models import User, Document, Doctor, Patient
from easyhealth_app.forms import DocumentForm, SignUpForm, LoginForm, AddDoctorForm
from easyhealth_app import bcrypt
from easyhealth_app.utils import patient_required, doctor_required
from easyhealth_app import app, db

auth = Blueprint("auth", __name__)
patients = Blueprint("patients", __name__)
doctors = Blueprint("doctors", __name__)

##########################################
#           Routes                       #
##########################################

@auth.route('/')
def homepage():
    documents = Document.query.all()
    return render_template('home.html', documents=documents)

@patients.route('/new_patient_document', methods=['GET', 'POST'])
@login_required
@patient_required
def new_patient_document():
    form = DocumentForm()

    if form.validate_on_submit(): 
    
        document = Document(
            title=form.title.data,
            pts_created=Patient.query.get(current_user.patient_ids),
            drs_created=Doctor.query.get(round(form.drs_created.data))

        )
        print(current_user.patient_ids)
        print(round(form.drs_created.data))

        db.session.add(document)
        db.session.commit()
        
        flash('New Document was successfully created')
        return redirect(url_for('patients.patient_document_detail', document_id=document.id))

    return render_template('new_patient_document.html', form=form)

@patients.route('/add_patient_doctor', methods=['GET', 'POST'])
@login_required
@patient_required
def add_patient_doctor():
    patient = Patient.query.get(current_user.patient_ids)
        #current_user.patients_ids
    form = AddDoctorForm(obj=patient)

    if form.validate_on_submit(): 
        patient.doctors_id = ([Doctor.query.get(form.doctor.data)])
    
    db.session.add(patient)
    db.session.commit()
        
    flash('A new Doctor was succesfully added.')

    return render_template('add_patient_doctor.html', patient=patient, form=form)

@doctors.route('/new_doctor_document', methods=['GET', 'POST'])
@login_required
@doctor_required
def new_doctor_document():
    form = DocumentForm()

    if form.validate_on_submit(): 
    
        document = Document(
            title=form.title.data,
            pts_created=Patient.query.get(current_user.doctor_ids),
            drs_created=Doctor.query.get(form.drs_created.data)
        )

        db.session.add(document)
        db.session.commit()
        
        flash('New Document was successfully created')
        return redirect(url_for('doctors.doctor_document_detail', document_id=document.id))

    return render_template('new_doctor_document.html', form=form)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            password=hashed_password,
            name=form.name.data,
            email=form.email.data,
            phone=form.phone.data,
            care_service=form.care_service.data,
            is_doctor=form.is_doctor.data,
            doctor_ids = -1,
            patient_ids = -1
        )

        db.session.add(user)
        db.session.commit()

        if user.is_doctor == True:
            doctor = Doctor(
                username=form.username.data,
                password=hashed_password,
                name=form.name.data,
                email=form.email.data,
                phone=form.phone.data,
                care_service=form.care_service.data
            )

            db.session.add(doctor)
            db.session.commit()
            user.doctor_ids=doctor.id

            db.session.add(user)
            db.session.commit()

        elif user.is_doctor == False:
            patient = Patient(
                username=form.username.data,
                password=hashed_password,
                name=form.name.data,
                email=form.email.data,
                phone=form.phone.data,
                care_service=form.care_service.data
            )

            db.session.add(patient)
            db.session.commit()

            user.patient_ids = patient.id
            db.session.add(user)
            db.session.commit()
        
        flash('Account Created.')

        db.session.commit()

        return redirect(url_for('auth.login'))
    print(form.errors)
    return render_template('signup.html', form=form)

@doctors.route('/doctor_document_detail/<document_id>', methods=['GET', 'POST'])
@login_required
@doctor_required
def doctor_document_detail(document_id):
    document = Document.query.get(document_id)
    form = DocumentForm(obj=document)

    if form.validate_on_submit():
        document.title=(form.title.data)
        document.pts_created=(Patient.query.get(form.pts_created.data))
        document.drs_created=(Doctor.query.get(current_user.doctor_id))

    db.session.add(document)
    db.session.commit()
    flash('A new Doctor Document was successfully updated')

    document = Document.query.get(document_id)
    return render_template('doctor_document_detail.html', document=document, form=form)

@patients.route('/patient_document_detail/<document_id>', methods=['GET', 'POST'])
@login_required
@patient_required
def patient_document_detail(document_id):
    document = Document.query.filter_by(id=document_id).one()
    form = DocumentForm(obj=document)

    if form.validate_on_submit():
        document.title=(form.title.data)
        document.pts_created=(Patient.query.get(current_user.patient_ids))
        document.drs_created=(Doctor.query.get(form.drs_created.data))

    db.session.add(document)
    db.session.commit()
    flash('A new Patient Document was successfully updated')

    document = Document.query.get(document_id)
    return render_template('patient_document_detail.html', document=document, form=form)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('auth.homepage'))
    return render_template('login.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.homepage'))

easyhealth_app/templates/add_patient_doctor.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" action = "{{ url_for('patients.add_patient_doctor', patient_ids=patient.id) }}">
        {{ form.csrf_token }} 
    
        <fieldset>
            <legend>Please enter the ID of your Doctor:</legend>
    
            <p><em>Form fields go here!</em></p>
            
            {% for error in form.doctor.errors %}
            <span class="error">*{{ error }}</span>
            {% endfor %}
            {{ form.doctor.label }}
            {{ form.doctor }}

            {{ form.submit }}

    
        </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>EasyHealth</title>
        <link rel="stylesheet" href="/static/style.css">
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>EasyHealth</title>
        
        <!-- BOOTSTRAP -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        
        <!-- BOOTSTRAP THEME (Downloaded from Themes website)-->
        <link rel="stylesheet" href="bootstrap.min.css">
        
        <!-- CUSTOM STYLES -->
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
        <link rel="stylesheet" href="style.css">
        
    </head>
   <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <a class="navbar-brand text-white" href="/">EasyHealth</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link text-light" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-light" href="/signup">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="/new_patient_document">Send Medical Document As Patient</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="/new_doctor_document">Send Document As Doctor</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="/add_patient_doctor">Add New Doctor</a>
                </li>
              </ul>
                <a class="nav-link text-light" href="/login">Login</a>
        
            </div>
          </nav>


            <div id="content">
                {% for message in get_flashed_messages() %}
                    {{ message }}
                {% endfor %}

                {% block content %}{% endblock %}
            </div>
            <script src="/static/index.js"></script>
    </body>
</html>

easyhealth_app/templates/doctor_document_detail.html
{% extends 'base.html' %}
{% block content %}


<form method="POST" action = "{{ url_for('doctors.doctor_document_detail', document_id=document.id) }}">
        {{ form.csrf_token }} 
    
        <fieldset>
            <legend>Please enter your information:</legend>
    
            <p><em>Form fields go here!</em></p>
            
            {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
            {% endfor %}
            {{ form.title.label }}
            {{ form.title }}

            {{ form.pts_created.label }}
            {{ form.pts_created }}

            {{ form.submit }}

    
        </fieldset>
</form>




{% endblock %}

easyhealth_app/templates/doctor_signup.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup_doctor" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.email.label }}
        {{ form.email }}
        <ul>
        {% for error in form.email.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.phone.label }}
        {{ form.phone }}
        <ul>
        {% for error in form.phone.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.care_service.label }}
        {{ form.care_service }}
        <ul>
        {% for error in form.care_service.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.credentials.label }}
        {{ form.credentials }}
        <ul>
        {% for error in form.credentials.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

easyhealth_app/templates/document_detail.html
{% extends 'base.html' %}
{% block content %}


<form method="POST" action = "{{ url_for('patients.document_detail', document_id=document.id) }}">
        {{ form.csrf_token }} 
    
        <fieldset>
            <legend>Please enter your information:</legend>
    
            <p><em>Form fields go here!</em></p>
            
            <!-- Uses the `form` object passed in from the route to render a form. -->
            {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
            {% endfor %}
            {{ form.title.label }}
            {{ form.title }}

            {{ form.pts_created.label }}
            {{ form.pts_created }}

            {{ form.drs_created.label }}
            {{ form.drs_created }}

            {{ form.submit }}

    
        </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
 <!-- HERO -->
 <div class="jumbotron text-center hero-background-img">
    <h1 class = "text-info">Welcome to EasyHealth!</h1>
</div>
<div class="row m-5">  

    {% for document in documents %}
            {% if not current_user.is_doctor %}
                 
                    <div class="card mb-4 md-2 m-5 lg-6" style="width: 18rem; ">
                        <div class="card-body">
                            <a href="/patient_document_detail/{{ document.id }}">{{ document.title }}</a>  
                    
                        </div>
                    </div>

            {% endif %}
            
            {% if current_user.is_doctor %}
                <a href="/doctor_document_detail/{{ document.id }}">{{ document.title }}</a> 
            {% endif %}

    {% endfor %}
</div>



{% endblock %}

easyhealth_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<!-- TODO: Fill in the sign up form here! -->

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>
{% endblock %}

easyhealth_app/templates/new_doctor_document.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="{{ url_for('doctors.new_doctor_document') }}">
    {{ form.csrf_token }} 

    <fieldset>
        <legend>Please enter your information:</legend>

        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        <p><em>Form fields go here!</em></p>
        
        <!-- Uses the `form` object passed in from the route to render a form. -->
        {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.pts_created.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}

        {{ form.pts_created.label }}
        {{ form.pts_created }}

        {{ form.submit }}



    </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/new_document.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="{{ url_for('patients.new_document') }}">
    {{ form.csrf_token }} 

    <fieldset>
        <legend>Please enter your information:</legend>

        <!-- TODO: Remove the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        <p><em>Form fields go here!</em></p>
        
        <!-- Uses the `form` object passed in from the route to render a form. -->
        {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.file_url.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.file_url.label }}
        {{ form.file_url }}

        {{ form.doctor_id.label }}
        {{ form.doctor_id }}

        {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/new_patient_document.html
{% extends 'base.html' %}
{% block content %}

<h1>New Document</h1>

<form method="POST" action="{{ url_for('patients.new_patient_document') }}">
    {{ form.csrf_token }} 

    <fieldset>
        <legend>Please enter your information:</legend>

        <p><em>Form fields go here!</em></p>
        
        {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.title.label }}
        {{ form.title }}

        {% for error in form.drs_created.errors %}
        <span class="error">*{{ error }}</span>
        {% endfor %}

        {{ form.drs_created.label }}
        {{ form.drs_created }}

        {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/patient_document_detail.html
{% extends 'base.html' %}
{% block content %}


<form method="POST" action = "{{ url_for('patients.patient_document_detail', document_id=document.id) }}">
        {{ form.csrf_token }} 
    
        <fieldset>
            <legend>Please enter your information:</legend>
    
            <p><em>Form fields go here!</em></p>
            
            <!-- Uses the `form` object passed in from the route to render a form. -->
            {% for error in form.title.errors %}
            <span class="error">*{{ error }}</span>
            {% endfor %}
            
            {{ form.title.label }}
            {{ form.title }}

            {{ form.drs_created.label }}
            {{ form.drs_created }}

            {{ form.submit }}

        </fieldset>
</form>


{% endblock %}

easyhealth_app/templates/patient_signup.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup_patient" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>


        {{ form.email.label }}
        {{ form.email }}
        <ul>
        {% for error in form.email.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

easyhealth_app/templates/signup.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
        {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.email.label }}
        {{ form.email }}
        <ul>
        {% for error in form.email.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {% for error in form.phone.errors %}
        <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.phone.label }}
        {{ form.phone }}

        {% for error in form.care_service.errors %}
        <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.care_service.label }}
        {{ form.care_service }}

        
        {% for error in form.is_doctor.errors %}
        <span class="error">*{{ error }}</span>
        {% endfor %}
        {{ form.is_doctor.label }}
        {{ form.is_doctor }}

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}